name: 'Pollapo install'
description: 'Pollapo install'
inputs:
  out-dir:
    description: 'Out directory'
    required: false
    default: .pollapo
  token:
    description: 'Github OAuth token'
    required: true
  config:
    description: 'Pollapo config'
    required: false
    default: pollapo.yml
  working-directory:
    description: 'Working directory'
    required: false
    default: .
  runs-on-option:
    description: 'runs-on option'
    required: false
    default: 'ubuntu'
runs:
  using: 'node12'
  main: 'dist/index.js'
